#! /bin/bash

# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the
# "License"). You may not use this file except in compliance
#  with the License. A copy of the License is located at
#
#     http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and
# limitations under the License.

AWS_REGION="${1:-}"
AWS_ACCOUNT_ID="${2:-}"

images="registry:2.7.0
golang:1.15.4
gcc:7.3.0
busybox:1.32.0
amazonlinux:2.0.20200722.0
amazon/aws-for-fluent-bit:2.7.0"

usage() {
    cat <<EOF
Usage: ${0} AWS_REGION AWS_ACCOUNT_ID

This script attempts to pull the following dockerhub images from ECR:

$images

It assumes that the ECR images will be formatted like:

AWS_ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com/ci/IMAGE_OS/IMAGE_ARCH/IMAGE_NAME

(see ci-ecr-push for creating these)
EOF
}

if [ -z "$AWS_REGION" ]; then
    usage
    exit 1
fi

if [ -z "$AWS_ACCOUNT_ID" ]; then
    usage
    exit 1
fi

ECR_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"

aws --region "$AWS_REGION" ecr get-login-password | docker login --username AWS --password-stdin "$ECR_URI"

for image in $images; do
    imageArch=$(docker version --format "{{.Server.Arch}}")
    imageOS=$(docker version --format "{{.Server.Os}}")
    fullRepoName="ci/$imageOS/$imageArch/$image"
    fullURI="$ECR_URI/$fullRepoName"
    echo "PULLING: $fullURI"
    docker pull "$fullURI"
    docker tag "$fullURI" "$image"
done
